"""Build latex/references.bib from screening.csv using the publishers' own metadata.

For each included key, BibTeX is fetched from https://doi.org by content negotiation
(Crossref and DataCite both answer), the entry key is replaced with ours, and a
`verified` field is added: yes only if the abstract was read (screening.csv).
Grey literature (event sources, tools) comes from grey_literature.bib, written by hand
from pages we opened. Papers whose peer-reviewed venue registers no DOI (e.g. ICLR, USENIX)
come from venue_versions.bib, copied from the official proceedings pages; they replace the
arXiv record for the same key. Nothing is typed from memory.
"""
from __future__ import annotations

import csv
import re
import sys
import time
import urllib.request
from pathlib import Path

HERE = Path(__file__).resolve().parent
OUT = HERE.parent / "latex" / "references.bib"


def bibtex(doi: str) -> str:
    req = urllib.request.Request("https://doi.org/" + doi, headers={
        "Accept": "application/x-bibtex; charset=utf-8", "User-Agent": "hackalem-lit-review/1.0"})
    with urllib.request.urlopen(req, timeout=40) as r:
        return r.read().decode("utf-8")


def tidy(raw: str) -> str:
    """Drop fields that repeat the DOI or add clutter, and use TeX quotes in titles."""
    raw = re.sub(r"\bISSN\s*=\s*\{[^}]*\},\s*", "", raw)
    raw = re.sub(r"\burl\s*=\s*\{https?://(?:dx\.)?doi\.org/[^}]*\},\s*", "", raw)
    raw = re.sub(r"(\btitle\s*=\s*\{[^\n]*?)\?:", r"\1?", raw)  # Crossref joins title and subtitle as "?:"
    return re.sub(r"(\btitle\s*=\s*\{[^\n]*?)\"([^\"\n]*)\"", r"\1``\2''", raw)


def offline() -> None:
    """Re-apply tidy() and the current grey literature without fetching again."""
    grey = (HERE / "grey_literature.bib").read_text(encoding="utf-8")
    generated = OUT.read_text(encoding="utf-8").split("% Grey literature:")[0].rstrip() + "\n"
    OUT.write_text(tidy(generated) + "\n" + grey, encoding="utf-8")
    print(f"rewrote {OUT} offline")


def main() -> None:
    if "--offline" in sys.argv:
        return offline()
    venue = {m.group(1): m.group(0) for m in re.finditer(
        r"@\w+\{(\w+),.*?\n\}", (HERE / "venue_versions.bib").read_text(encoding="utf-8"), flags=re.S)}
    rows = [r for r in csv.DictReader((HERE / "screening.csv").open(encoding="utf-8")) if r["include"] == "include"]
    parts = ["% Generated by literature/build_bib.py from publisher metadata (doi.org). Do not edit by hand.\n"]
    for r in rows:
        if r["key"] in venue:
            parts.append(venue[r["key"]] + "\n")
            print(f"{r['key']}: venue version")
            continue
        raw = bibtex(r["doi_or_url"]).strip()
        raw = re.sub(r"^@(\w+)\{[^,]*,", lambda m: f"@{m.group(1).lower()}{{{r['key']},", raw, count=1)
        # keep the publisher's capitalisation (e.g. GitHub, SWE-bench): wrap the title in braces
        raw = re.sub(r"(\btitle\s*=\s*)\{(.*?)\}(,\s*(?:volume|ISSN|url|DOI|publisher|journal|booktitle|series|number|author|year|note|howpublished|copyright|keywords)\b)",
                     lambda m: m.group(1) + "{{" + m.group(2) + "}}" + m.group(3), raw, count=1, flags=re.S)
        if r["doi_or_url"].lower().startswith("10.48550/arxiv."):
            arxiv_id = r["doi_or_url"].split(".", 2)[-1]
            raw = raw.rstrip().rstrip("}").rstrip().rstrip(",") + f",\n  howpublished = {{arXiv preprint arXiv:{arxiv_id}}}\n}}"
        months = {m: m[:3].lower() for m in ["January", "February", "March", "April", "May", "June", "July",
                                               "August", "September", "October", "November", "December"]}
        raw = re.sub(r"month\s*=\s*\{?([A-Za-z]+)\}?", lambda m: "month=" + months.get(m.group(1).capitalize(), m.group(1).lower()[:3]), raw)
        verified = "yes" if r["abstract_read"] == "yes" else "no"
        raw = raw.rstrip("}").rstrip().rstrip(",") + f",\n  verified = {{{verified}}}\n}}"
        if "doi =" not in raw.lower() and "doi=" not in raw.lower():
            raw = raw.rstrip("}").rstrip() + f",\n  doi = {{{r['doi_or_url']}}}\n}}"
        parts.append(tidy(raw) + "\n")
        print(f"{r['key']}: ok")
        time.sleep(0.3)
    grey = (HERE / "grey_literature.bib").read_text(encoding="utf-8")
    OUT.write_text("\n".join(parts) + "\n" + grey, encoding="utf-8")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
