"""Build latex/references.bib from screening.csv using the publishers' own metadata.

For each included key, BibTeX is fetched from https://doi.org by content negotiation
(Crossref and DataCite both answer), the entry key is replaced with ours, and a
`verified` field is added: yes only if the abstract was read (screening.csv).
Grey literature (event sources, tools) comes from grey_literature.bib, written by hand
from pages we opened. Papers whose peer-reviewed venue registers no DOI (e.g. ICLR, USENIX)
come from venue_versions.bib, copied from the official proceedings pages; they replace the
arXiv record for the same key. Nothing is typed from memory.
"""
from __future__ import annotations

import csv
import re
import sys
import time
import urllib.request
from pathlib import Path

HERE = Path(__file__).resolve().parent
OUT = HERE.parent / "latex" / "references.bib"


def bibtex(doi: str) -> str:
    req = urllib.request.Request("https://doi.org/" + doi, headers={
        "Accept": "application/x-bibtex; charset=utf-8", "User-Agent": "hackalem-lit-review/1.0"})
    with urllib.request.urlopen(req, timeout=40) as r:
        return r.read().decode("utf-8")


def dedupe_authors(raw: str) -> str:
    m = re.search(r"(\bauthor\s*=\s*\{)(.*?)(\}\s*,)", raw, flags=re.S)
    if not m:
        return raw
    names, seen = [], set()
    for n in m.group(2).split(" and "):
        if n.strip() not in seen:
            seen.add(n.strip())
            names.append(n.strip())
    return raw[:m.start(2)] + " and ".join(names) + raw[m.end(2):]


def arxiv_doi(raw: str) -> str:
    """Print the arXiv DOI of a preprint (in howpublished) and drop the URL that repeats it."""
    m = re.search(r"howpublished = \{arXiv preprint arXiv:([0-9.]+)\}", raw)
    if not m:
        return raw
    aid = m.group(1)
    raw = raw.replace(m.group(0), f"howpublished = {{arXiv preprint arXiv:{aid}, \\doi{{10.48550/arXiv.{aid}}}}}")
    return re.sub(r"\s*url = \{https://arxiv\.org/abs/[^}]*\},", "", raw)


YEAR_OF_ISSUE = {"10.1007/s10664-018-9660-3": "2019"}  # online 2018, journal issue 24(3), 2019

# Corrections to the Crossref records, each checked against the publisher's page (literature/reference_audit.md).
FIXES = {
    "10.1145/2597073.2597074": [("ICSE ’14", "MSR 2014")],                   # MSR 2014, not ICSE
    "10.1109/msr52588.2021.00020": [("Hackathon Code Where", "Hackathon Code: Where")],
    "10.1145/3833089.3833091": [("Game Jams Hackathons", "Game Jams, Hackathons")],
    "10.1145/1584322.1584325": [("Proceedings of the fifth international workshop on Computing education research workshop",
                                 "Proceedings of the Fifth International Workshop on Computing Education Research Workshop")],
}
ARTICLE_NUMBER = {"10.1007/s10664-022-10201-x": "167", "10.1007/s10664-021-10072-8": "94"}  # Crossref article-number


def tidy(raw: str) -> str:
    """Drop fields that repeat the DOI or add clutter, and use TeX quotes in titles."""
    raw = arxiv_doi(dedupe_authors(raw))
    for doi, year in YEAR_OF_ISSUE.items():
        if doi.lower() in raw.lower():
            raw = re.sub(r"year\s*=\s*\{\d{4}\}", "year={" + year + "}", raw, count=1)
    for doi, fixes in FIXES.items():
        if doi.lower() in raw.lower():
            for a, b in fixes:
                raw = raw.replace(a, b)
    for doi, number in ARTICLE_NUMBER.items():
        if doi.lower() in raw.lower() and not re.search(r"\bpages\s*=", raw):
            raw = re.sub(r"(\bnumber\s*=\s*\{[^}]*\},)", r"\1 pages={" + number + "},", raw, count=1)
    raw = re.sub(r"(\bpages\s*=\s*\{[^}]*?)–", r"\1--", raw)  # a Unicode dash is not read as a range
    raw = re.sub(r"\bISSN\s*=\s*\{[^}]*\},\s*", "", raw)
    raw = re.sub(r"\burl\s*=\s*\{https?://(?:dx\.)?doi\.org/[^}]*\},\s*", "", raw)
    raw = re.sub(r"(\btitle\s*=\s*\{[^\n]*?)\?:", r"\1?", raw)  # Crossref joins title and subtitle as "?:"
    return re.sub(r"(\btitle\s*=\s*\{[^\n]*?)\"([^\"\n]*)\"", r"\1``\2''", raw)


def offline() -> None:
    """Re-apply tidy() and the current grey literature without fetching again."""
    grey = (HERE / "grey_literature.bib").read_text(encoding="utf-8")
    generated = OUT.read_text(encoding="utf-8").split("% Grey literature:")[0].rstrip() + "\n"
    head, *entries = generated.split("\n@")
    generated = "\n@".join([head] + [tidy(e) for e in entries])
    OUT.write_text(generated + "\n" + grey, encoding="utf-8")
    print(f"rewrote {OUT} offline")


def main() -> None:
    if "--offline" in sys.argv:
        return offline()
    venue = {m.group(1): m.group(0) for m in re.finditer(
        r"@\w+\{(\w+),.*?\n\}", (HERE / "venue_versions.bib").read_text(encoding="utf-8"), flags=re.S)}
    rows = [r for r in csv.DictReader((HERE / "screening.csv").open(encoding="utf-8")) if r["include"] == "include"]
    parts = ["% Generated by literature/build_bib.py from publisher metadata (doi.org). Do not edit by hand.\n"]
    for r in rows:
        if r["key"] in venue:
            parts.append(venue[r["key"]] + "\n")
            print(f"{r['key']}: venue version")
            continue
        raw = bibtex(r["doi_or_url"]).strip()
        raw = re.sub(r"^@(\w+)\{[^,]*,", lambda m: f"@{m.group(1).lower()}{{{r['key']},", raw, count=1)
        # keep the publisher's capitalisation (e.g. GitHub, SWE-bench): wrap the title in braces
        raw = re.sub(r"(\btitle\s*=\s*)\{(.*?)\}(,\s*(?:volume|ISSN|url|DOI|publisher|journal|booktitle|series|number|author|year|note|howpublished|copyright|keywords)\b)",
                     lambda m: m.group(1) + "{{" + m.group(2) + "}}" + m.group(3), raw, count=1, flags=re.S)
        if r["doi_or_url"].lower().startswith("10.48550/arxiv."):
            arxiv_id = r["doi_or_url"].split(".", 2)[-1]
            raw = raw.rstrip().rstrip("}").rstrip().rstrip(",") + f",\n  howpublished = {{arXiv preprint arXiv:{arxiv_id}}}\n}}"
        months = {m: m[:3].lower() for m in ["January", "February", "March", "April", "May", "June", "July",
                                               "August", "September", "October", "November", "December"]}
        raw = re.sub(r"month\s*=\s*\{?([A-Za-z]+)\}?", lambda m: "month=" + months.get(m.group(1).capitalize(), m.group(1).lower()[:3]), raw)
        verified = "yes" if r["abstract_read"] == "yes" else "no"
        raw = raw.rstrip("}").rstrip().rstrip(",") + f",\n  verified = {{{verified}}}\n}}"
        if "doi =" not in raw.lower() and "doi=" not in raw.lower():
            raw = raw.rstrip("}").rstrip() + f",\n  doi = {{{r['doi_or_url']}}}\n}}"
        parts.append(tidy(raw) + "\n")
        print(f"{r['key']}: ok")
        time.sleep(0.3)
    grey = (HERE / "grey_literature.bib").read_text(encoding="utf-8")
    OUT.write_text("\n".join(parts) + "\n" + grey, encoding="utf-8")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
