"""Turn the paper's facts file into LaTeX macros (latex/numbers.tex).

Each numeric fact becomes one macro, e.g. repos_total -> \\NReposTotal, and
case_counts["07"] -> \\NCaseCountsZeroSeven. Numbers are wrapped in \\num{} so
siunitx prints thousands separators; decimals are read as written in the facts
file, so trailing zeros survive (60.0, 1.170). Text in the paper must use these
macros instead of typed numbers.

Source: analysis/facts_paper.json. Until M1 rebuilds it from the clones, the
verified public facts in charts/bilingual/facts.json are used (with a warning).
"""
from __future__ import annotations

import json
import re
import sys
from decimal import Decimal
from pathlib import Path

PAPER = Path(__file__).resolve().parent.parent
ROOT = PAPER.parent
PRIMARY = PAPER / "analysis" / "facts_paper.json"
FALLBACK = ROOT / "charts" / "bilingual" / "facts.json"
OUT = PAPER / "latex" / "numbers.tex"

DIGITS = ["Zero", "One", "Two", "Three", "Four", "Five", "Six", "Seven", "Eight", "Nine"]


def macro_name(parts: list[str]) -> str:
    words = []
    for part in parts:
        for token in re.split(r"[^A-Za-z0-9]+", part):
            if not token:
                continue
            spelled = "".join(DIGITS[int(ch)] if ch.isdigit() else ch for ch in token)
            words.append(spelled[0].upper() + spelled[1:])
    return "N" + "".join(words)


def render(value) -> str | None:
    if isinstance(value, bool):
        return None
    if isinstance(value, int):
        return rf"\num{{{value}}}"
    if isinstance(value, Decimal):
        return rf"\num{{{value}}}"
    if isinstance(value, str):
        return value.replace("_", r"\_")
    return None


def flatten(prefix: list[str], value, out: dict) -> None:
    if isinstance(value, dict):
        for key, inner in value.items():
            flatten(prefix + [str(key)], inner, out)
    else:
        rendered = render(value)
        if rendered is not None:
            out[macro_name(prefix)] = rendered


def main() -> int:
    source = PRIMARY if PRIMARY.exists() else FALLBACK
    if source is FALLBACK:
        print(f"warning: {PRIMARY.name} not found; using interim {FALLBACK.relative_to(ROOT)}")
    facts = json.loads(source.read_text(encoding="utf-8"), parse_float=Decimal)
    macros: dict[str, str] = {}
    flatten([], facts, macros)
    lines = [
        "% Generated by analysis/make_numbers.py. Do not edit by hand.",
        f"% Source: {source.relative_to(ROOT)}",
    ]
    lines += [rf"\newcommand{{\{name}}}{{{value}}}" for name, value in sorted(macros.items())]
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {len(macros)} macros -> {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
